---
- name: Create Development directory if it does not exist
  file:
    path: ~/Development
    state: directory
    mode: '0755'

- name: Check for dotfiles repo exist (for development)
  stat:
    path: ~/Development/dotfiles
  register: p

- name: Clone dotfiles repo
  git:
    repo: https://github.com/tinhtruong/dotfiles.git
    dest: ~/Development/dotfiles
    accept_hostkey: yes
  when: not p.stat.exists
  become: false

- name: Link dotfiles to user home using GNU stow
  shell: "cd ~/Development/dotfiles && ls | xargs /opt/homebrew/bin/stow --verbose --target={{ lookup('env','HOME') }}/ --restow"
  become:  false
