---
- name: "Check if fish shell is already registered in /etc/shells"
  become: yes
  lineinfile:
    path: /etc/shells
    line: "fish"
    state: present
  check_mode: yes
  register: fish_not_registered

- name: "Register fish shell in /etc/shells"
  command: echo /opt/homebrew/bin/fish >> /etc/shells
  when: fish_not_registered
  become: yes

- name: "Make fish the default shell"
  command: chsh -s /opt/homebrew/bin/fish
  become: yes