---
- name: Copy .osx customisation script to home directory
  copy:
    src: "files/.osx"
    dest: "~/"
    mode: '0744'

# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx customisation script.
  command: "~/.osx"
  changed_when: false

- name: Update Key Binding settings for Home/End
  copy:
    src: "files/DefaultKeyBinding.dict"
    dest: "~/Library/KeyBindings/"
    mode: '0644'
